# Generated by Django 3.2 on 2023-07-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
    ]
